force-app/main/default/objects/Adyen_Adapter__mdt/fields/Auto_Capture_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Auto_Capture_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To identify if Auto Capture is enabled in Customer Area</description>
    <inlineHelpText>Check if Auto Capture (Immediate capture) is enabled in Adyen Customer Area</inlineHelpText>
    <label>Auto Capture Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Manual_Capture_Payment_Methods__c.field-meta.xml
<CustomField>
    <fullName>Manual_Capture_Payment_Methods__c</fullName>
    <description>Comma-separated list of payment methods that require manual capture.</description>
    <inlineHelpText>Enter a comma-separated list of payment methods that require manual capture.</inlineHelpText>
    <label>Manual Capture Payment Methods</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Package_Namespace__c.field-meta.xml
<CustomField>
    <fullName>Package_Namespace__c</fullName>
    <description>For Adyen adyen_payment namespace</description>
    <inlineHelpText>Do not change this value</inlineHelpText>
    <label>Package Namespace</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Payment_Link_Expiry_Duration__c.field-meta.xml
<CustomField>
    <fullName>Payment_Link_Expiry_Duration__c</fullName>
    <description>Expiration time of the payment link in days</description>
    <label>Payment Link Expiry Duration</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Payment_Link_Return_Url__c.field-meta.xml
<CustomField>
    <fullName>Payment_Link_Return_Url__c</fullName>
    <description>Website URL used for redirection after payment is completed</description>
    <label>Payment Link Return Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Payment_Link_Theme_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Link_Theme_Id__c</fullName>
    <label>Payment Link Theme Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/System_Integrator_Name__c.field-meta.xml
<CustomField>
    <fullName>System_Integrator_Name__c</fullName>
    <description>Name of the System Integrator, working with the Merchant on installing and enabling the package</description>
    <inlineHelpText>Name of the System Integrator, working with the Merchant on installing and enabling the package</inlineHelpText>
    <label>System Integrator Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdyenCustomMetadataService.cls
public with sharing class AdyenCustomMetadataService {
   
    public static Adyen_Adapter__mdt getDefaultAdapter() {
        Map<String, Object> adapterData = new Map<String, Object>();

        try {
            Adyen_Adapter__mdt defaultAdapter = [
                SELECT Id, DeveloperName, MasterLabel, Package_Namespace__c,
                Merchant_Account__c, HMAC_Key__c, Auto_Capture_Enabled__c,
                Manual_Capture_Payment_Methods__c, System_Integrator_Name__c,
                Payment_Link_Return_Url__c, Payment_Link_Theme_Id__c,
                Payment_Link_Expiry_Duration__c
                FROM Adyen_Adapter__mdt
                WHERE DeveloperName = :AdyenConstants.DEFAULT_ADAPTER_NAME
                LIMIT 1
            ];

            return defaultAdapter;
            
        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving Adyen adapter: ' + e.getMessage());
        }
    }

    public static String updateDefaultAdapter(Adyen_Adapter__mdt adapterData) {
        try {
            if (adapterData == null) {
                throw new HandledException('Please provide a valid adapter data.');
            }
            Adyen_Adapter__mdt defaultAdapter = [
                SELECT DeveloperName, MasterLabel, Package_Namespace__c
                FROM Adyen_Adapter__mdt
                WHERE DeveloperName = :AdyenConstants.DEFAULT_ADAPTER_NAME
                LIMIT 1
            ];

            Metadata.DeployContainer mdContainer = new Metadata.DeployContainer();
            String namespacePrefix = String.isNotBlank(defaultAdapter.Package_Namespace__c) ? defaultAdapter.Package_Namespace__c + '__' : '';
            
            Metadata.CustomMetadata adapterMetadata = new Metadata.CustomMetadata();
            adapterMetadata.fullName = namespacePrefix + 'Adyen_Adapter__mdt.' + namespacePrefix + AdyenConstants.DEFAULT_ADAPTER_NAME;
            adapterMetadata.label = defaultAdapter.MasterLabel;

            adapterMetadata.values = new List<Metadata.CustomMetadataValue>();

            addFieldIfNotNull(adapterMetadata, namespacePrefix + 'Merchant_Account__c', adapterData.Merchant_Account__c);
            addFieldIfNotNull(adapterMetadata, namespacePrefix + 'HMAC_Key__c', adapterData.HMAC_Key__c);
            addFieldIfNotNull(adapterMetadata, namespacePrefix + 'Auto_Capture_Enabled__c', adapterData.Auto_Capture_Enabled__c);
            addFieldIfNotNull(adapterMetadata, namespacePrefix + 'Manual_Capture_Payment_Methods__c', adapterData.Manual_Capture_Payment_Methods__c);
            addFieldIfNotNull(adapterMetadata, namespacePrefix + 'System_Integrator_Name__c', adapterData.System_Integrator_Name__c);
            addFieldIfNotNull(adapterMetadata, namespacePrefix + 'Payment_Link_Return_Url__c', adapterData.Payment_Link_Return_Url__c);
            addFieldIfNotNull(adapterMetadata, namespacePrefix + 'Payment_Link_Theme_Id__c', adapterData.Payment_Link_Theme_Id__c);
            addFieldIfNotNull(adapterMetadata, namespacePrefix + 'Payment_Link_Expiry_Duration__c', adapterData.Payment_Link_Expiry_Duration__c);

            mdContainer.addMetadata(adapterMetadata);

            Id deploymentId = deployMetadataWithCallback(mdContainer);
            return String.valueOf(deploymentId);

        } catch (Exception e) {
            throw new AuraHandledException('Error updating Adyen adapter: ' + e.getMessage());
        }
    }

    private static void addFieldIfNotNull(Metadata.CustomMetadata metadata, String fieldName, Object fieldValue) {
        if (fieldValue != null) {
            Metadata.CustomMetadataValue mdField = new Metadata.CustomMetadataValue();
            mdField.field = fieldName;
            mdField.value = fieldValue;
            metadata.values.add(mdField);
        }
    }

    private static Id deployMetadataWithCallback(metadata.DeployContainer mdContainer) {
        if (Test.isRunningTest() && TestDataFactory.isMetadataAPISuccessful) {
            return TestDataFactory.mockDeploymentId;
        }

        AdyenMetadataDeployCallback callback = new AdyenMetadataDeployCallback();
        return Metadata.Operations.enqueueDeployment(mdContainer, callback);
    }
}