force-app/main/default/objects/Adyen_Adapter__mdt/fields/Endpoint_Api_Version__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_Api_Version__c</fullName>
    <description>The Api Version of the Endpoint, e.g. v52</description>
    <inlineHelpText>The Api Version of the Endpoint, e.g. v52</inlineHelpText>
    <label>Endpoint Api Version</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Package_Namespace__c.field-meta.xml
<CustomField>
    <fullName>Package_Namespace__c</fullName>
    <description>For Adyen adyen_payment namespace</description>
    <inlineHelpText>Do not change this value</inlineHelpText>
    <label>Package Namespace</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Payment_Link_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Payment_Link_Endpoint__c</fullName>
    <description>Endpoint used to create a payment link</description>
    <label>Payment Link Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Payment_Link_Expiry_Duration__c.field-meta.xml
<CustomField>
    <fullName>Payment_Link_Expiry_Duration__c</fullName>
    <description>Expiration time of the payment link in days</description>
    <label>Payment Link Expiry Duration</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Payment_Link_Return_Url__c.field-meta.xml
<CustomField>
    <fullName>Payment_Link_Return_Url__c</fullName>
    <description>Website URL used for redirection after payment is completed</description>
    <label>Payment Link Return Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Payment_Link_Theme_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Link_Theme_Id__c</fullName>
    <label>Payment Link Theme Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/System_Integrator_Name__c.field-meta.xml
<CustomField>
    <fullName>System_Integrator_Name__c</fullName>
    <description>Name of the System Integrator, working with the Merchant on installing and enabling the package</description>
    <inlineHelpText>Name of the System Integrator, working with the Merchant on installing and enabling the package</inlineHelpText>
    <label>System Integrator Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdyenPBLHelper.cls
public with sharing class AdyenPBLHelper {
    public static final List<String> ALLOWED_PAYMENT_METHODS = new List<String>{'ideal', 'scheme', 'paypal', 'applepay'};

    public static PaymentLinkRequest buildPaymentLinkRequest(Adyen_Adapter__mdt adyenAdapter, Amount amount, String reference) {
        PaymentLinkRequest paymentLinkRequest = new PaymentLinkRequest();
        paymentLinkRequest.amount = amount;
        paymentLinkRequest.reference = reference;
        paymentLinkRequest.merchantAccount = adyenAdapter.Merchant_Account__c;
        paymentLinkRequest.applicationInfo = AdyenPaymentUtility.getApplicationInfo(adyenAdapter.System_Integrator_Name__c);
        paymentLinkRequest.returnUrl = adyenAdapter.Payment_Link_Return_Url__c;
        paymentLinkRequest.themeId = adyenAdapter.Payment_Link_Theme_Id__c;
        paymentLinkRequest.allowedPaymentMethods = ALLOWED_PAYMENT_METHODS;
        paymentLinkRequest.expiresAt = adyenAdapter.Payment_Link_Expiry_Duration__c != null 
            ? getLinkExpiryDate(adyenAdapter.Payment_Link_Expiry_Duration__c.intValue()) 
            : null;

        return paymentLinkRequest;
    } 

    public static PaymentLinkResponse generatePaymentLink(Adyen_Adapter__mdt adyenAdapter, PaymentLinkRequest paymentLinkRequest) {
        if (adyenAdapter == null || paymentLinkRequest == null) {
            throw new IllegalArgumentException('One or more input parameters are null');
        }

        try {
            String endpoint = buildEndpoint(adyenAdapter, 'Payment_Link_Endpoint__c');
            String body = AdyenPaymentUtility.makeAdyenCompatible(JSON.serialize(paymentLinkRequest, true));

            HttpRequest request = new HttpRequest();
            request.setEndpoint(endpoint);
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/json');
            request.setBody(body);

            HttpResponse response = new Http().send(request);

            if (response.getStatusCode() != 201) {
                throw new AdyenGatewayAdapter.GatewayException('Adyen Checkout API returned: ' + response.getStatusCode() + ', body: ' + response.getBody());
            } else {
                String salesforceCompatibleBody = AdyenPaymentUtility.makeSalesforceCompatible(response.getBody());
                PaymentLinkResponse paymentLinkResponse = (PaymentLinkResponse)JSON.deserialize(salesforceCompatibleBody, PaymentLinkResponse.class);
                return paymentLinkResponse;
            }
        } catch (Exception e) {
            throw new AdyenGatewayAdapter.GatewayException('Error generating payment link: ' + e.getMessage());
        }
    }

    private static String buildEndpoint(Adyen_Adapter__mdt adyenAdapter, String endpointFieldName) {
        String namedCredential = adyenAdapter.Named_Credential__c;
        String namespace = String.isNotBlank(adyenAdapter.Package_Namespace__c) ? adyenAdapter.Package_Namespace__c + '__' : '';
        String endpointUrl = 'callout:' + namespace + namedCredential;
        String apiVersion = adyenAdapter.Endpoint_Api_Version__c;
        String endpointPath = (String) adyenAdapter.get(endpointFieldName);

        return endpointUrl + apiVersion + endpointPath;
    }
    
    @TestVisible
    private static String getLinkExpiryDate(Integer days) {
        Datetime currentDateTime = Datetime.now();
        Datetime expiryDateTime = currentDateTime.addDays(days);

        return formatDateTimeToISO8601(expiryDateTime);
    }

    private static String formatDateTimeToISO8601(Datetime dt) {
        String iso8601Date = dt.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss');
        String timeZoneOffset = Datetime.now().format('Z');
        String formattedOffset = timeZoneOffset.substring(0, 3) + ':' + timeZoneOffset.substring(3);

        return iso8601Date + formattedOffset;
    }
}