force-app/main/default/objects/Adyen_Adapter__mdt/fields/Management_API_Endpoint_Path__c.field-meta.xml
<CustomField>
    <fullName>Management_API_Endpoint_Path__c</fullName>
    <label>Management API Endpoint Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Management_API_Named_Credential__c.field-meta.xml
<CustomField>
    <fullName>Management_API_Named_Credential__c</fullName>
    <description>Named Credential for the Adyen Management API</description>
    <inlineHelpText>Named Credential name for the Adyen Management API</inlineHelpText>
    <label>Management API Named Credential</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Management_API_Version__c.field-meta.xml
<CustomField>
    <fullName>Management_API_Version__c</fullName>
    <description>Version of the Adyen Management API</description>
    <inlineHelpText>Version of the Adyen Management API</inlineHelpText>
    <label>Management API Version</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Management_API_Webhook_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Management_API_Webhook_Endpoint__c</fullName>
    <label>Management API Webhook Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Package_Namespace__c.field-meta.xml
<CustomField>
    <fullName>Package_Namespace__c</fullName>
    <description>For Adyen adyen_payment namespace</description>
    <inlineHelpText>Do not change this value</inlineHelpText>
    <label>Package Namespace</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdyenWebhookServiceTest.cls
@IsTest
private class AdyenWebhookServiceTest {
    
    @IsTest
    static void setupWebhookSuccessTest() {
        // Given
        AdyenWebhookService.mockAdapter = new Adyen_Adapter__mdt(
            Merchant_Account__c = 'TestMerchant',
            Management_API_Named_Credential__c = 'TestCredential',
            Management_API_Version__c = 'v3',
            Management_API_Webhook_Endpoint__c = '/{merchantId}/webhooks',
            Management_API_Endpoint_Path__c = '/merchants',
            Package_Namespace__c = ''
        );

        String webhookUrl = 'https://testwebhook.com';
        List<String> eventCodes = new List<String>{'AUTHORISATION'};
        String description = 'Test webhook';

        Test.setMock(HttpCalloutMock.class, new TestDataFactory.WebhookSetupMockResponse());

        // When
        Test.startTest();
        WebhookSetupResponse response = AdyenWebhookService.setupWebhook(AdyenWebhookService.mockAdapter, webhookUrl, eventCodes, description);
        Test.stopTest();

        // Then
        Assert.areNotEqual(response, null);
        Assert.areEqual(description, response.description);
    }

    @IsTest
    static void setupWebhookMissingMerchantAccountTest() {
        // Given & When
        Test.startTest();
        try {
            AdyenWebhookService.setupWebhook(null, 'https://testwebhook.com', new List<String>{'AUTHORISATION'}, 'Test');
            Assert.fail('Expected Exception was not thrown');
        } catch (Exception e) {
            // Then
            Assert.isInstanceOfType(e, AdyenWebhookService.AdyenWebhookException.class);
        }
        Test.stopTest();
    }

    @IsTest
    static void setupWebhookHttpFailureTest() {
        // Given
        AdyenWebhookService.mockAdapter = new Adyen_Adapter__mdt(
                Merchant_Account__c = 'TestMerchant',
                Management_API_Named_Credential__c = 'TestCredential',
                Management_API_Version__c = 'v3',
                Management_API_Webhook_Endpoint__c = '/{merchantId}/webhooks',
                Management_API_Endpoint_Path__c = '/merchants',
                Package_Namespace__c = ''
            );
        Test.setMock(HttpCalloutMock.class, new TestDataFactory.FailureResponse());

        // When
        Test.startTest();
        try {
            AdyenWebhookService.setupWebhook(AdyenWebhookService.mockAdapter, 'https://testwebhook.com', new List<String>{'AUTHORISATION'}, 'Test');
            Assert.fail('Expected Exception was not thrown');
        } catch (Exception e) {
            // Then
            Assert.isInstanceOfType(e, AdyenWebhookService.AdyenWebhookException.class);
        }
        Test.stopTest();
    }
}