force-app/main/default/objects/Adyen_Metadata_Deployment_Result__e/Adyen_Metadata_Deployment_Result__e.object-meta.xml
<CustomObject>
    <label>Adyen Metadata Deployment Result</label>
    <pluralLabel>Adyen Metadata Deployment Results</pluralLabel>
</CustomObject>

force-app/main/default/objects/Adyen_Metadata_Deployment_Result__e/fields/Deployment_Id__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Id__c</fullName>
    <label>Deployment ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Metadata_Deployment_Result__e/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Metadata_Deployment_Result__e/fields/Is_Success__c.field-meta.xml
<CustomField>
    <fullName>Is_Success__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Success</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AdyenMetadataDeployCallback.cls
public class AdyenMetadataDeployCallback implements Metadata.DeployCallback {

    public void handleResult(Metadata.DeployResult result, Metadata.DeployCallbackContext context) {
        Adyen_Metadata_Deployment_Result__e deploymentEvent = new Adyen_Metadata_Deployment_Result__e(
            Deployment_Id__c = result.id,
            Is_Success__c = (result.status == Metadata.DeployStatus.Succeeded),
            Error_Message__c = result.status == Metadata.DeployStatus.Succeeded ? null : result.errorMessage
        );

        EventBus.publish(deploymentEvent);
    }
}