force-app/main/default/objects/Payment_Link__c/Payment_Link__c.object-meta.xml
<CustomObject>
    <description>Custom Object used to store details about the Adyen payment by link solution</description>
    <label>Payment Link</label>
    <nameField>
        <label>Payment Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Link__c/fields/Expire_Date__c.field-meta.xml
<CustomField>
    <fullName>Expire_Date__c</fullName>
    <label>Expiry Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment_Link__c/fields/Order_Summary__c.field-meta.xml
<CustomField>
    <fullName>Order_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>Payment Links</relationshipLabel>
    <relationshipName>Payment_Links</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Link__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Payment_Pending</fullName>
                <label>Payment Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentLinkExpireAction.cls
global with sharing class PaymentLinkExpireAction {
    @InvocableMethod(Label = 'Force Expire Link' Category = 'Payment Link' Callout = true)
    global static void forceExpireLink(List<PBLForceExpire> pblForceExpireList) {
        if (pblForceExpireList == null || pblForceExpireList.isEmpty() || pblForceExpireList[0].orderSummaryId == null) {
            throw new IllegalArgumentException('Required order summary Id is missing!');
        }

        String expiredStatus = AdyenOMSConstants.PaymentLinkStatus.EXPIRED.name();
        String activeStatus = AdyenOMSConstants.PaymentLinkStatus.ACTIVE.name();
        Adyen_Adapter__mdt adyenAdapter = AdyenPaymentUtility.retrieveAdapterByDeveloperName(AdyenConstants.DEFAULT_ADAPTER_NAME);
        Id orderSummaryId = pblForceExpireList[0].orderSummaryId;

        List<Payment_Link__c> activePaymentLinks = [
                SELECT Name, Expire_Date__c
                FROM Payment_Link__c
                WHERE Order_Summary__c = :orderSummaryId AND Status__c LIKE :activeStatus
        ];
        for (Payment_Link__c activeLink : activePaymentLinks) {
            if (activeLink.Expire_Date__c > Datetime.now()) { // expire date in the future
                Map<String,String> expirePatchBody = new Map<String, String>{ 'status' => expiredStatus.toLowerCase() };
                AdyenPBLHelper.sendLinkPatchRequest(adyenAdapter, activeLink.Name, JSON.serialize(expirePatchBody));
            }
            activeLink.Status__c = expiredStatus;
        }
        update activePaymentLinks;
    }

    global class PBLForceExpire {
        @InvocableVariable(Required=true)
        public Id orderSummaryId;
    }
}