force-app/main/default/objects/Payment_Link__c/Payment_Link__c.object-meta.xml
<CustomObject>
    <description>Custom Object used to store details about the Adyen payment by link solution</description>
    <label>Payment Link</label>
    <nameField>
        <label>Payment Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Link__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Payment_Pending</fullName>
                <label>Payment Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdyenPBLControllerTest.cls
@IsTest
public class AdyenPBLControllerTest {

    @IsTest
    static void updatePaymentLinkStatusSuccessTest() {
        // Given
        Payment_Link__c paymentLink = new Payment_Link__c(
            Name = 'PLE5B4575C5A026A2B2',
            Status__c = 'Active'
        );
        insert paymentLink;

        Test.setMock(HttpCalloutMock.class, new TestDataFactory.PBLExpiredMockResponse());

        // When
        Test.startTest();
        AdyenPBLController.updatePaymentLinkStatus(paymentLink.Id);
        Test.stopTest();

        // Then
        Payment_Link__c updatedPaymentLink = [SELECT Status__c FROM Payment_Link__c WHERE Id = :paymentLink.Id];
        Assert.areEqual('Expired', updatedPaymentLink.Status__c, 'The payment link status should be updated to Expired.');
    }

    @IsTest
    static void updatePaymentLinkStatusInvalidLinkTest() {
        // Given
        // No Payment Link ID provided (null case)

        // When & Then
        try {
            AdyenPBLController.updatePaymentLinkStatus(null);
            Assert.fail('Exception was not thrown');
        } catch (AuraHandledException e) {
            Assert.isTrue(
                e.getMessage().contains('Script-thrown exception'),
                'Expected a script-thrown exception message.'
            );
        }
    }

}