force-app/main/default/objects/Payment_Link__c/Payment_Link__c.object-meta.xml
<CustomObject>
    <description>Custom Object used to store details about the Adyen payment by link solution</description>
    <label>Payment Link</label>
    <nameField>
        <label>Payment Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Link__c/fields/Expire_Date__c.field-meta.xml
<CustomField>
    <fullName>Expire_Date__c</fullName>
    <label>Expiry Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment_Link__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Payment_Pending</fullName>
                <label>Payment Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdyenPaymentLinkBatch.cls
public class AdyenPaymentLinkBatch implements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext batchContext) {
        return Database.getQueryLocator([
            SELECT Id, Expire_Date__c, Status__c 
            FROM Payment_Link__c 
            WHERE Status__c = 'Active'
        ]);
    }

    public void execute(Database.BatchableContext batchContext, List<Payment_Link__c> paymentLinkRecords) {
        List<Payment_Link__c> paymentLinksToExpire = new List<Payment_Link__c>();
        
        for (Payment_Link__c paymentLinkRecord : paymentLinkRecords) {
            if (paymentLinkRecord.Expire_Date__c != null && paymentLinkRecord.Expire_Date__c <= System.now()) {
                paymentLinkRecord.Status__c = AdyenOMSConstants.PaymentLinkStatus.EXPIRED.name();
                paymentLinksToExpire.add(paymentLinkRecord);
            }
        }

        if (!paymentLinksToExpire.isEmpty()) {
            update paymentLinksToExpire;
        }
    }

    public void finish(Database.BatchableContext batchContext) {
        // No additional logic needed after batch execution
    }
}