force-app/main/default/objects/Payment_Link__c/Payment_Link__c.object-meta.xml
<CustomObject>
    <description>Custom Object used to store details about the Adyen payment by link solution</description>
    <label>Payment Link</label>
    <nameField>
        <label>Payment Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Link__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Payment_Pending</fullName>
                <label>Payment Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdyenPBLController.cls
public with sharing class AdyenPBLController {
    
    @AuraEnabled
    public static void updatePaymentLinkStatus(Id paymentLinkId) {

        if (paymentLinkId == null) {
            throw new AuraHandledException('Invalid Payment Link ID.');
        }
    
        try {

            Payment_Link__c paymentLink = [SELECT Id, Status__c, Name FROM Payment_Link__c WHERE Id = :paymentLinkId LIMIT 1];
            
            Adyen_Adapter__mdt adyenAdapter = AdyenPaymentUtility.retrieveAdapterByDeveloperName(AdyenConstants.DEFAULT_ADAPTER_NAME);
            PaymentLinkResponse paymentLinkResponse = AdyenPBLHelper.getPaymentLinkById(adyenAdapter, paymentLink?.Name);
            String latestStatus = paymentLinkResponse.status; 
            
            if (latestStatus != null && AdyenOMSConstants.ADYEN_PBL_STATUS_TO_SF_STATUS.containsKey(latestStatus)) {
                paymentLink.Status__c = AdyenOMSConstants.ADYEN_PBL_STATUS_TO_SF_STATUS.get(latestStatus);
            }

            update paymentLink;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}