force-app/main/default/objects/Payment_Link__c/Payment_Link__c.object-meta.xml
<CustomObject>
    <description>Custom Object used to store details about the Adyen payment by link solution</description>
    <label>Payment Link</label>
    <nameField>
        <label>Payment Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Link__c/fields/Expire_Date__c.field-meta.xml
<CustomField>
    <fullName>Expire_Date__c</fullName>
    <label>Expiry Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment_Link__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Payment_Pending</fullName>
                <label>Payment Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdyenPaymentLinkBatchTest.cls
@IsTest
private class AdyenPaymentLinkBatchTest {
    
    @IsTest
    static void expiredLinkTest() {
        // Given
        List<Payment_Link__c> paymentLinks = new List<Payment_Link__c>();
        
        paymentLinks.add(new Payment_Link__c(
            Expire_Date__c = System.now().addDays(-1),
            Status__c = 'Active'
        ));
        paymentLinks.add(new Payment_Link__c(
            Expire_Date__c = System.now().addDays(1),
            Status__c = 'Active'
        ));
        
        insert paymentLinks;
        
        // When
        AdyenPaymentLinkBatch batch = new AdyenPaymentLinkBatch();
        Test.startTest();
        Database.executeBatch(batch);
        Test.stopTest();
        
        // Then
        List<Payment_Link__c> updatedLinks = [SELECT Id, Status__c FROM Payment_Link__c];
        Assert.areEqual(updatedLinks[0].Status__c, 'Expired');
        Assert.areEqual(updatedLinks[1].Status__c, 'Active');
    }

    @IsTest
    static void noExpiredLinksTest() {
        // Given
        List<Payment_Link__c> paymentLinks = new List<Payment_Link__c>();
        
        paymentLinks.add(new Payment_Link__c(
            Expire_Date__c = System.now().addDays(1),
            Status__c = 'Active'
        ));
        paymentLinks.add(new Payment_Link__c(
            Expire_Date__c = System.now().addDays(2),
            Status__c = 'Active'
        ));

        insert paymentLinks;
        
        // When
        AdyenPaymentLinkBatch batch = new AdyenPaymentLinkBatch();
        Test.startTest();
        Database.executeBatch(batch);
        Test.stopTest();
        
        // Then
        List<Payment_Link__c> updatedLinks = [SELECT Id, Status__c FROM Payment_Link__c];
        Assert.areEqual(updatedLinks[0].Status__c, 'Active');
        Assert.areEqual(updatedLinks[1].Status__c, 'Active');
    }

    @IsTest
    static void nullExpireDateTest() {
        // Given
        insert new Payment_Link__c(Status__c = 'Active');
        
        // When
        AdyenPaymentLinkBatch batch = new AdyenPaymentLinkBatch();
        Test.startTest();
        Database.executeBatch(batch);
        Test.stopTest();

        // Then
        Payment_Link__c link = [SELECT Status__c FROM Payment_Link__c LIMIT 1];
        Assert.areEqual('Active', link.Status__c);
    }
    
}